# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180412_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='gender',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
