# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20180418_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.AddField(
            model_name='review',
            name='age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='gender',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
